import { v4 as  uuidv4 } from 'uuid' ;  
export const DataShop = [ 
	{ 
		id : uuidv4() , 
		img : "./img/product-1.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 2 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-2.jpg" , 
		name : "Nokia Lumia 1320" ,   
		price : 899.99 , 
		price_sale : "$999.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-3.jpg" , 
		name : "LG Leon 2015" ,   
		price : 499.99 , 
		price_sale : "$425.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-4.jpg" , 
		name : "Sony microsoft" ,   
		price : 299.99 , 
		price_sale : "$225.99<" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-5.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-1.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-2.jpg" , 
		name : "Nokia Lumia 1320" ,   
		price : 899.99 , 
		price_sale : "$999.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-3.jpg" , 
		name : "LG Leon 2015" ,   
		price : 499.99 , 
		price_sale : "$425.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-4.jpg" , 
		name : "Sony microsoft" ,   
		price : 299.99 , 
		price_sale : "$225.99<" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-5.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-1.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-2.jpg" , 
		name : "Nokia Lumia 1320" ,   
		price : "$899.99" , 
		price_sale : "$999.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-1.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 2 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-2.jpg" , 
		name : "Nokia Lumia 1320" ,   
		price : 899.99 , 
		price_sale : "$999.99" ,  
		quantity : 1 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-1.jpg" , 
		name : "Samsung Galaxy s5- 2015" ,   
		price : 799.99 , 
		price_sale :  "$199.99" ,  
		quantity : 2 ,  
	} , 
	{ 
		id : uuidv4() , 
		img : "./img/product-2.jpg" , 
		name : "Nokia Lumia 1320" ,   
		price : 899.99 , 
		price_sale : "$999.99" ,  
		quantity : 1 ,  
	} , 
	 
]  